---
# tasks file for jobtracker

- name: Hadoop MAPRED JobTracker
  debug:
    msg: "Hadoop MAPRED JobTracker Configuration"

- name: Download Java Software
  get_url:
    url: https://mirrors.huaweicloud.com/java/jdk/8u171-b11/jdk-8u171-linux-x64.rpm
    dest: /root/java.rpm
  register: x

- debug:
    var: x.msg

- name: Download Hadoop Software
  get_url:
    url: https://archive.apache.org/dist/hadoop/core/hadoop-1.2.1/hadoop-1.2.1-1.x86_64.rpm
    dest: /root/hadoop.rpm
  register: y

- debug:
    var: y.msg

- name: Installing Java Software
  command: "rpm -ivh /root/java.rpm"
  register: java

- debug:
    var: java.stdout

- name: Installing Hadoop Software
  command: "rpm -ivh /root/hadoop.rpm --force"
  register: hadoop
  when: java.rc == 0
    
- debug:
    var: hadoop.stdout

- name: Configuring mapred-site.xml
  blockinfile:
    path: /etc/hadoop/mapred-site.xml
    insertafter: "<configuration>"
    block:
      <property>
      <name>mapred.job.tracker</name>
      <value>hdfs://0.0.0.0:9001</value>
      </property>

- name: Configuring core-site.xml
  blockinfile:
    path: /etc/hadoop/core-site.xml
    insertafter: "<configuration>"
    block:
       <property>
       <name>fs.default.name</name>
       <value>hdfs://{{ hostvars[groups['namenode'][0]]['ansible_default_ipv4']['address'] }}:9001</value>
       </property>

- name: Starting Job Tracker services
  shell: "hadoop-daemon.sh start jobtracker"
  register: service
    
- debug:
    var: service

- name: Checking status of Job Tracker Services
  shell: "jps"
  register: jps
    
- debug:
    var: jps.stdout_lines

- name: Setting up JobTracker services permanent   
  shell: "echo -e hadoop-daemon.sh start jobtracker >> /etc/rc.local"

- name: Hadoop MAPRED JobTracker Success Message
  debug:
    var: "Hadoop MAPRED JobTracker Configured Successfully.......!!"
